global using GamePlayer = Virial.Game.Player;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using Virial.Assignable;
global using Nebula.Utilities;
global using Virial.Events.Role;
global using Virial;
global using Virial.Attributes;
global using Virial.Events.Player;
global using Virial.Game;
global using Virial.Configuration;
global using Virial.Components;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using UnityEngine;
global using TMPro;
global using Nebula.Modules.ScriptComponents;
global using Nebula.Roles.Impostor;
global using Virial.Events.Game.Meeting;
global using Virial.Events.Game;
global using HarmonyLib;
global using Nebula.Configuration;
global using BepInEx.Unity.IL2CPP.Utils;
global using Nebula.Roles;
global using Nebula.Extensions;
global using Virial.Media;
global using BepInEx.Unity.IL2CPP.Utils.Collections;
global using Virial.Compat;
global using Nebula.Modules;
global using Nebula.Game;
global using Nebula.Game.Statistics;
global using Nebula.Player;
global using Nebula.Roles.Neutral;
global using Virial.Utilities;
global using Nebula.Roles.Modifier;
global using Nebula.Roles.Abilities;
global using Nebula.Behavior;
global using Nebula.Modules.GUIWidget;
global using Nebula;
global using Hazel;
global using Nebula.Roles.Crewmate;
global using Virial.Text;
global using Virial.DI;
global using Il2CppSystem.Threading.Tasks;
global using System.Text;
global using System.Security.Cryptography;
global using VVector2 = Virial.Compat.Vector2;
global using VVector3 = Virial.Compat.Vector3;
global using VVector4 = Virial.Compat.Vector4;
global using VColor = Virial.Color;
